### ISSUE TITLE
Pack variables are not being added to a platform when using boo template

### ISSUE THREAD

**Issue by jvanzyl** [oneops/boo#8]
```
Mssql pack has 2 variables defined in the pack metadata like this:
variable 'temp_drive',
:description => 'Temp Drive',
:value => 'T'
variable 'data_drive',
:description => 'Data Drive',
:value => 'F'
When I use a simple boo template (attached as mssql1.yaml) an assembly and environment are created, but the pack variables are not added to the platform. Therefore all components using the variables fail in the transition phase.
Boo output:
vagrant@vagrant:~/bfd-oneops-templates$ boo -f mssql1.yaml --create
Configuration file: /home/vagrant/bfd-oneops-templates/mssql1.yaml
1%
5% **
Creating platform pSqlServer ...
Created platform pSqlServer.
Updating component mssql for pSqlServer ...
Updating component database for pSqlServer ...
15% *******
20% **********
Creating the environment devndc1.
30% ***************
40% ********************
50% *************************
70% ***********************************
Starting the deployment now.
100% **************************************************
No deployment needed!
Oneops url: https://oneops.prod.walmart.com/oneops/assemblies/209484674/transition/environments/209485221
If I change the boo template to add variables directly in the template then boo fails at design phase saying that the variables already exist.
```

Using the following Boo template:

```yaml
boo:
  oneops_host: '{{host}}'
  organization: '{{organization}}'
  api_key: '{{api_key}}'
  email: '{{email}}'
  environment_name: 'devndc1' # All the deployment in this template adds to this environment.
  ip_output: 'json'
 
assembly:
  name: 'test-mssql-boo'
  auto_gen: false # If turn on, then this tool will generate random assembly name for you.
 
platforms: # In OneOps design.
  pSqlServer:
    deploy_order: 1
    pack: oneops/mssql
    pack_version: '1'
    components:
      mssql:
        password: 'Walmart_1'
      database:
        password: 'Walmart_1'
environment:
  global_dns: 'true'
  availability: 'single'
  subdomain: 'devndc.test-mssql-boo' # environment_name.assembly_name
  profile: 'DEV'
  clouds: # Can support multiple clouds (the sum of pct_scale should be 100, currently priority and dpmt_order should be both 1)
    dev-ndc1:
      priority: '1'
      dpmt_order: '1'
      pct_scale: '100'
```
